version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: education_portal
      POSTGRES_USER: kiadev
      POSTGRES_PASSWORD: secret